/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardOfficerRouteImport } from './routes/ward-officer'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ReportRouteImport } from './routes/report'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DepartmentHeadRouteImport } from './routes/department-head'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const WardOfficerRoute = WardOfficerRouteImport.update({
  id: '/ward-officer',
  path: '/ward-officer',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentHeadRoute = DepartmentHeadRouteImport.update({
  id: '/department-head',
  path: '/department-head',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/department-head': typeof DepartmentHeadRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRoute
  '/track': typeof TrackRoute
  '/ward-officer': typeof WardOfficerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/department-head': typeof DepartmentHeadRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRoute
  '/track': typeof TrackRoute
  '/ward-officer': typeof WardOfficerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/department-head': typeof DepartmentHeadRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRoute
  '/track': typeof TrackRoute
  '/ward-officer': typeof WardOfficerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/department-head'
    | '/login'
    | '/map'
    | '/report'
    | '/track'
    | '/ward-officer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/department-head'
    | '/login'
    | '/map'
    | '/report'
    | '/track'
    | '/ward-officer'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/department-head'
    | '/login'
    | '/map'
    | '/report'
    | '/track'
    | '/ward-officer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DepartmentHeadRoute: typeof DepartmentHeadRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ReportRoute: typeof ReportRoute
  TrackRoute: typeof TrackRoute
  WardOfficerRoute: typeof WardOfficerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ward-officer': {
      id: '/ward-officer'
      path: '/ward-officer'
      fullPath: '/ward-officer'
      preLoaderRoute: typeof WardOfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/department-head': {
      id: '/department-head'
      path: '/department-head'
      fullPath: '/department-head'
      preLoaderRoute: typeof DepartmentHeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DepartmentHeadRoute: DepartmentHeadRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ReportRoute: ReportRoute,
  TrackRoute: TrackRoute,
  WardOfficerRoute: WardOfficerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
